### ISSUE TITLE
Android & IOS Support

### ISSUE THREAD

**Issue by naziur604** [net-byte/vTunnel#1]
mostly android device not work like Chinese ROM device.
is there any way to make this tool IOS version?

**Comment by naziur604** [comment]
> > mostly android device not work like Chinese ROM device. is there any way to make this tool IOS version?
> 
> I am not an iOS developer, maybe I will learn Swift in the future.

can you send me a email naziur0707@gmail.com so we can talk more.
i want to make some change on this project for my personal use.
add auth/log/connection status/live user/ etc/

also i want to make this one openwrt version. it have to work small size tplink router like tplink mr-3420 v5
i dont have any way to talk to you so may be we can talk over email about more.
or you can send me your skype id.
its an paid work.
thank you.

**Comment by net-byte** [comment]
> openwrt & mac both connected fine but issue is its not pass any data need to config routing. like if i connect to openwrt its can ping to server but my all lan connected device dont change any IP all data have to pass over the tunnel and it have to use my server IP. if you can please give me the routing config or add it default .

#routing all your traffic on linux or openwrt:
ip route add 0.0.0.0/1 dev $1 
ip route add 128.0.0.0/1 dev $1 
ip route delete $2/32 via $3 dev $4
ip route add $2/32 via $3 dev $4

#routing all your traffic on mac:
/sbin/route add 192.168.1.0/24 -interface $5
/sbin/route add 0.0.0.0/0 -interface $1

$1   The vtun interface(tun0)
$2   The vtun server ip
$3   IP of your local network gateway(192.168.1.1)
$4   The local network interface(ens3)
$5   IP of vtun gateway(172.16.0.0)

Try this,but i have no openwrt or mac os to test it.
