### ISSUE TITLE
App bypass it self

### ISSUE THREAD

**Issue by PayaMousavi** [net-byte/vTunnel#4]
Hi,
It's better to use:
https://developer.android.com/reference/android/net/VpnService#protect(java.net.Socket) or https://developer.android.com/reference/android/net/VpnService#protect(int)
for having vpn socket to the server
there some use cases that i need to request some blocked websites from the app and your implementation to bypassing app itself wouldn't work

**Comment by net-byte** [comment]
I used a third-party websocket client library that can't get the socket.
