### ISSUE TITLE
No internet

### ISSUE THREAD

**Issue by tormentous** [net-byte/vTunnel#5]
Sir, we followed instructions for creating the server, made a little a adjustments in getting the Local IP, run the app it connects but has no internet.

**Comment by net-byte** [comment]
did you enable IP forwarding on server?
sudo echo 1 > /proc/sys/net/ipv4/ip_forward
sudo sysctl -p
// eth0 is the name of your public network interface
sudo iptables -t nat -A POSTROUTING -s 172.16.0.0/24 -o eth0 -j MASQUERADE

**Comment by tormentous** [comment]
> did you enable IP forwarding on server?
> sudo echo 1 > /proc/sys/net/ipv4/ip_forward
> sudo sysctl -p
> // eth0 is the name of your public network interface
> sudo iptables -t nat -A POSTROUTING -s 172.16.0.0/24 -o eth0 -j MASQU

Yes we did

**Comment by tormentous** [comment]
sorry it was the adjustment on local ip that was making the error.
